name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt --check
        run: cargo fmt --check

      - name: Run cargo clippy -- -D warnings
        run: cargo clippy -- -D warnings

      - name: Run cargo check
        run: cargo check

      - name: Run unit tests
        run: cargo test

      - name: Build release version
        run: cargo build --release

